export const dom = {
  campusSelect: document.getElementById("campusSelect"),
  buildingSelect: document.getElementById("buildingSelect"),
  structureSelect: document.getElementById("structureSelect"),
  floorSelect: document.getElementById("floorSelect"),
  clearCampusBtn: document.getElementById("clearCampusBtn"),
  clearBuildingBtn: document.getElementById("clearBuildingBtn"),
  clearStructureBtn: document.getElementById("clearStructureBtn"),
  clearFloorBtn: document.getElementById("clearFloorBtn"),
  pathText: document.getElementById("pathText"),
  emptyStateText: document.getElementById("emptyStateText"),
  deleteBranchBtn: document.getElementById("deleteBranchBtn"),
  contentGrid: document.getElementById("contentGrid"),
  hierarchyMidRow: document.getElementById("hierarchyMidRow"),
  entityEditCard: document.getElementById("entityEditCard"),
  entityEditTitle: document.getElementById("entityEditTitle"),
  entityEditReadId: document.getElementById("entityEditReadId"),
  entityEditReadType: document.getElementById("entityEditReadType"),
  entityEditReadKind: document.getElementById("entityEditReadKind"),
  entityEditPhotoEmpty: document.getElementById("entityEditPhotoEmpty"),
  entityEditPhotoLink: document.getElementById("entityEditPhotoLink"),
  entityEditForm: document.getElementById("entityEditForm"),
  entityEditNumber: document.getElementById("entityEditNumber"),
  entityEditShortName: document.getElementById("entityEditShortName"),
  entityEditFullName: document.getElementById("entityEditFullName"),
  entityEditDescription: document.getElementById("entityEditDescription"),
  entityEditAddress: document.getElementById("entityEditAddress"),
  modalOverlay: document.getElementById("modalOverlay"),
  editObjectForm: document.getElementById("editObjectForm"),
  editObjectKind: document.getElementById("editObjectKind"),
  editObjectName: document.getElementById("editObjectName"),
  cancelEditObjectBtn: document.getElementById("cancelEditObjectBtn"),
  imageModalOverlay: document.getElementById("imageModalOverlay"),
  imageModalStage: document.getElementById("imageModalStage"),
  imageModalImg: document.getElementById("imageModalImg"),
  imageModalMarkers: document.getElementById("imageModalMarkers"),
  imageModalHint: document.getElementById("imageModalHint"),
  closeImageModalBtn: document.getElementById("closeImageModalBtn"),
  confirmOverlay: document.getElementById("confirmOverlay"),
  confirmTitle: document.getElementById("confirmTitle"),
  confirmMessage: document.getElementById("confirmMessage"),
  confirmCancelBtn: document.getElementById("confirmCancelBtn"),
  confirmOkBtn: document.getElementById("confirmOkBtn"),
  entityMetaOverlay: document.getElementById("entityMetaOverlay"),
  entityMetaForm: document.getElementById("entityMetaForm"),
  entityMetaTitle: document.getElementById("entityMetaTitle"),
  entityMetaNumber: document.getElementById("entityMetaNumber"),
  entityMetaShortName: document.getElementById("entityMetaShortName"),
  entityMetaFullName: document.getElementById("entityMetaFullName"),
  entityMetaDescription: document.getElementById("entityMetaDescription"),
  entityMetaAddressWrap: document.getElementById("entityMetaAddressWrap"),
  entityMetaAddress: document.getElementById("entityMetaAddress"),
  entityMetaDrawingWrap: document.getElementById("entityMetaDrawingWrap"),
  entityMetaDrawingFile: document.getElementById("entityMetaDrawingFile"),
  entityMetaCancelBtn: document.getElementById("entityMetaCancelBtn"),
  photoCard: document.getElementById("photoCard"),
  photoCardTitle: document.getElementById("photoCardTitle"),
  createEntityCard: document.getElementById("createEntityCard"),
  createEntityTitle: document.getElementById("createEntityTitle"),
  rightCard: document.getElementById("rightCard"),
  planStage: document.getElementById("planStage"),
  planImage: document.getElementById("planImage"),
  planMarkers: document.getElementById("planMarkers"),
  planHint: document.getElementById("planHint"),
  planMarkerLegend: document.getElementById("planMarkerLegend"),
  imageForm: document.getElementById("imageForm"),
  imageInput: document.getElementById("imageInput"),
  downloadImageBtn: document.getElementById("downloadImageBtn"),
  deleteImageBtn: document.getElementById("deleteImageBtn"),
  objectForm: document.getElementById("objectForm"),
  kindSelect: document.getElementById("kindSelect"),
  nameInput: document.getElementById("nameInput"),
  objectsTbody: document.getElementById("objectsTbody"),
  zoneManagement: document.getElementById("zoneManagement"),
  dictionariesManagement: document.getElementById("dictionariesManagement"),
  objectTypeForm: document.getElementById("objectTypeForm"),
  objectTypeNameInput: document.getElementById("objectTypeNameInput"),
  objectTypesTbody: document.getElementById("objectTypesTbody"),
  objectKindForm: document.getElementById("objectKindForm"),
  objectKindTypeSelect: document.getElementById("objectKindTypeSelect"),
  objectKindNameInput: document.getElementById("objectKindNameInput"),
  objectKindsTbody: document.getElementById("objectKindsTbody"),
  pageTitle: document.getElementById("pageTitle"),
  rightCardTitle: document.getElementById("rightCardTitle"),
  createCampusBlock: document.getElementById("createCampusBlock"),
  photoBlock: document.getElementById("photoBlock"),
  createChildBlock: document.getElementById("createChildBlock"),
  createCampusForm: document.getElementById("createCampusForm"),
  createCampusName: document.getElementById("createCampusName"),
  createBuildingForm: document.getElementById("createBuildingForm"),
  createBuildingName: document.getElementById("createBuildingName"),
  createStructureForm: document.getElementById("createStructureForm"),
  createStructureName: document.getElementById("createStructureName"),
  createFloorForm: document.getElementById("createFloorForm"),
  createFloorName: document.getElementById("createFloorName"),
};

export function fillSelect(selectEl, items, placeholder, disabled = false) {
  selectEl.innerHTML = "";
  const first = document.createElement("option");
  first.value = "";
  first.textContent = placeholder;
  first.disabled = true;
  first.selected = true;
  first.hidden = true;
  selectEl.appendChild(first);
  for (const item of items) {
    const option = document.createElement("option");
    option.value = item.id;
    option.textContent = item.name;
    selectEl.appendChild(option);
  }
  selectEl.disabled = disabled || items.length === 0;
}

