export const dom = {
  campusSelect: document.getElementById("campusSelect"),
  buildingSelect: document.getElementById("buildingSelect"),
  structureSelect: document.getElementById("structureSelect"),
  floorSelect: document.getElementById("floorSelect"),
  treeBreadcrumb: document.getElementById("treeBreadcrumb"),
  treeHomeBtn: document.getElementById("treeHomeBtn"),
  pathText: document.getElementById("pathText"),
  globalSearchSection: document.getElementById("globalSearchSection"),
  globalSearchInput: document.getElementById("globalSearchInput"),
  globalSearchBtn: document.getElementById("globalSearchBtn"),
  globalSearchFilterBtn: document.getElementById("globalSearchFilterBtn"),
  globalSearchFilterPanel: document.getElementById("globalSearchFilterPanel"),
  globalSearchFilterHier: document.getElementById("globalSearchFilterHier"),
  globalSearchFilterTz: document.getElementById("globalSearchFilterTz"),
  globalSearchFilterRoom: document.getElementById("globalSearchFilterRoom"),
  globalSearchResults: document.getElementById("globalSearchResults"),
  emptyStateText: document.getElementById("emptyStateText"),
  deleteBranchBtn: document.getElementById("deleteBranchBtn"),
  contentGrid: document.getElementById("contentGrid"),
  dictCardsRow: document.getElementById("dictCardsRow"),
  planFloorTools: document.getElementById("planFloorTools"),
  entityEditCard: document.getElementById("entityEditCard"),
  entityEditCardBody: document.getElementById("entityEditCardBody"),
  entityEditToggleBtn: document.getElementById("entityEditToggleBtn"),
  entityEditTitle: document.getElementById("entityEditTitle"),
  entityEditReadId: document.getElementById("entityEditReadId"),
  entityEditReadType: document.getElementById("entityEditReadType"),
  entityEditReadKind: document.getElementById("entityEditReadKind"),
  entityEditPhotoEmpty: document.getElementById("entityEditPhotoEmpty"),
  entityEditPhotoLink: document.getElementById("entityEditPhotoLink"),
  entityEditForm: document.getElementById("entityEditForm"),
  entityEditShortName: document.getElementById("entityEditShortName"),
  entityEditFullName: document.getElementById("entityEditFullName"),
  entityEditDescription: document.getElementById("entityEditDescription"),
  entityEditAddress: document.getElementById("entityEditAddress"),
  entityEditUnsavedBanner: document.getElementById("entityEditUnsavedBanner"),
  imageModalOverlay: document.getElementById("imageModalOverlay"),
  imageModalStage: document.getElementById("imageModalStage"),
  imageModalImg: document.getElementById("imageModalImg"),
  imageModalMarkers: document.getElementById("imageModalMarkers"),
  imageModalHint: document.getElementById("imageModalHint"),
  closeImageModalBtn: document.getElementById("closeImageModalBtn"),
  confirmOverlay: document.getElementById("confirmOverlay"),
  confirmTitle: document.getElementById("confirmTitle"),
  confirmMessage: document.getElementById("confirmMessage"),
  confirmCancelBtn: document.getElementById("confirmCancelBtn"),
  confirmOkBtn: document.getElementById("confirmOkBtn"),
  entityMetaOverlay: document.getElementById("entityMetaOverlay"),
  entityMetaForm: document.getElementById("entityMetaForm"),
  entityMetaTitle: document.getElementById("entityMetaTitle"),
  entityMetaNumberLabel: document.getElementById("entityMetaNumberLabel"),
  entityMetaNumber: document.getElementById("entityMetaNumber"),
  entityMetaParentWrap: document.getElementById("entityMetaParentWrap"),
  entityMetaParentId: document.getElementById("entityMetaParentId"),
  entityMetaParentTypeWrap: document.getElementById("entityMetaParentTypeWrap"),
  entityMetaParentTypeId: document.getElementById("entityMetaParentTypeId"),
  entityMetaKindTypeWrap: document.getElementById("entityMetaKindTypeWrap"),
  entityMetaObjectTypeId: document.getElementById("entityMetaObjectTypeId"),
  entityMetaTypeWrap: document.getElementById("entityMetaTypeWrap"),
  entityMetaReadType: document.getElementById("entityMetaReadType"),
  entityMetaKindReadWrap: document.getElementById("entityMetaKindReadWrap"),
  entityMetaReadKind: document.getElementById("entityMetaReadKind"),
  entityMetaKindEditWrap: document.getElementById("entityMetaKindEditWrap"),
  entityMetaKindSelect: document.getElementById("entityMetaKindSelect"),
  entityMetaMarkerColorWrap: document.getElementById("entityMetaMarkerColorWrap"),
  entityMetaMarkerColor: document.getElementById("entityMetaMarkerColor"),
  entityMetaShortName: document.getElementById("entityMetaShortName"),
  entityMetaRoomDuplicateHint: document.getElementById("entityMetaRoomDuplicateHint"),
  entityMetaZoneDuplicateHint: document.getElementById("entityMetaZoneDuplicateHint"),
  entityMetaFullName: document.getElementById("entityMetaFullName"),
  entityMetaDescription: document.getElementById("entityMetaDescription"),
  entityMetaAddressWrap: document.getElementById("entityMetaAddressWrap"),
  entityMetaAddress: document.getElementById("entityMetaAddress"),
  entityMetaCancelBtn: document.getElementById("entityMetaCancelBtn"),
  photoCard: document.getElementById("photoCard"),
  photoCardTitle: document.getElementById("photoCardTitle"),
  createEntityCard: document.getElementById("createEntityCard"),
  createEntityTitle: document.getElementById("createEntityTitle"),
  rightCard: document.getElementById("rightCard"),
  planStage: document.getElementById("planStage"),
  planImage: document.getElementById("planImage"),
  planMarkers: document.getElementById("planMarkers"),
  planHint: document.getElementById("planHint"),
  planMarkerLegend: document.getElementById("planMarkerLegend"),
  planMarkerLegendToggle: document.getElementById("planMarkerLegendToggle"),
  imageForm: document.getElementById("imageForm"),
  imageInput: document.getElementById("imageInput"),
  downloadImageBtn: document.getElementById("downloadImageBtn"),
  planMarkerScaleWrap: document.getElementById("planMarkerScaleWrap"),
  planMarkerScale: document.getElementById("planMarkerScale"),
  deleteImageBtn: document.getElementById("deleteImageBtn"),
  objectForm: document.getElementById("objectForm"),
  kindSelect: document.getElementById("kindSelect"),
  nameInput: document.getElementById("nameInput"),
  zoneNameDuplicateHint: document.getElementById("zoneNameDuplicateHint"),
  zonesList: document.getElementById("zonesList"),
  zoneManagement: document.getElementById("zoneManagement"),
  objectTypesCard: document.getElementById("objectTypesCard"),
  objectKindsCard: document.getElementById("objectKindsCard"),
  objectTypesTbody: document.getElementById("objectTypesTbody"),
  objectKindForm: document.getElementById("objectKindForm"),
  objectKindTypeSelect: document.getElementById("objectKindTypeSelect"),
  objectKindNameInput: document.getElementById("objectKindNameInput"),
  objectKindsTbody: document.getElementById("objectKindsTbody"),
  pageTitle: document.getElementById("pageTitle"),
  rightCardTitle: document.getElementById("rightCardTitle"),
  createCampusBlock: document.getElementById("createCampusBlock"),
  photoBlock: document.getElementById("photoBlock"),
  createChildBlock: document.getElementById("createChildBlock"),
  createCampusForm: document.getElementById("createCampusForm"),
  createCampusName: document.getElementById("createCampusName"),
  createBuildingForm: document.getElementById("createBuildingForm"),
  createBuildingName: document.getElementById("createBuildingName"),
  createStructureForm: document.getElementById("createStructureForm"),
  createStructureName: document.getElementById("createStructureName"),
  createFloorForm: document.getElementById("createFloorForm"),
  createFloorName: document.getElementById("createFloorName"),
};

export function fillSelect(selectEl, items, placeholder, disabled = false, selectedId = null) {
  selectEl.innerHTML = "";
  const first = document.createElement("option");
  first.value = "";
  first.textContent = placeholder;
  first.disabled = true;
  first.selected = selectedId == null;
  first.hidden = true;
  selectEl.appendChild(first);
  for (const item of items) {
    const option = document.createElement("option");
    option.value = String(item.id);
    option.textContent = item.name;
    if (selectedId != null && Number(item.id) === Number(selectedId)) {
      option.selected = true;
    }
    selectEl.appendChild(option);
  }
  selectEl.disabled = disabled || items.length === 0;
}

